from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass(frozen=True)
class Request:
    """A staged service request generated by one user."""

    request_id: int
    source_node: int
    user_id: int
    service_id: int
    compute: np.ndarray
    input_data: float
    stage_data: np.ndarray

    @property
    def num_stages(self) -> int:
        return int(self.compute.shape[0])


class RequestGenerator:
    """Poisson arrivals with configurable slow-scale service distribution."""

    def __init__(self, cfg: dict, service_stages: list[int], users_per_node: int, rng: np.random.Generator):
        self.cfg = cfg
        self.service_stages = service_stages
        self.users_per_node = users_per_node
        self.rng = rng
        self.next_request_id = 0

        req_cfg = cfg["requests"]
        num_services = len(service_stages)
        max_stages = max(service_stages)

        self.compute_base = np.zeros((num_services, max_stages), dtype=np.float32)
        self.stage_data_base = np.zeros((num_services, max_stages - 1), dtype=np.float32)
        self.input_data_base = self.rng.uniform(
            req_cfg["input_data_min"], req_cfg["input_data_max"], size=num_services
        ).astype(np.float32)

        for i, stages in enumerate(service_stages):
            self.compute_base[i, :stages] = self.rng.uniform(
                req_cfg["compute_min"], req_cfg["compute_max"], size=stages
            )
            data = self.input_data_base[i]
            for j in range(stages - 1):
                decay = self.rng.uniform(req_cfg["stage_data_decay_min"], req_cfg["stage_data_decay_max"])
                data = max(0.25, data * decay)
                self.stage_data_base[i, j] = data

    def service_probabilities(self, slow_epoch: int | None = None) -> np.ndarray:
        dist_cfg = self.cfg["requests"].get("service_distribution", {"mode": "uniform"})
        num_services = len(self.service_stages)
        mode = dist_cfg.get("mode", "uniform")
        if mode == "uniform" or slow_epoch is None:
            return np.full(num_services, 1.0 / num_services, dtype=np.float32)

        if mode != "drifting":
            raise ValueError(f"Unsupported service_distribution.mode={mode!r}")

        strength = float(dist_cfg.get("drift_strength", 0.35))
        period = max(float(dist_cfg.get("drift_period", 8)), 1.0)
        phase = 2.0 * np.pi * (float(slow_epoch) / period)
        offsets = 2.0 * np.pi * np.arange(num_services, dtype=np.float32) / float(num_services)
        weights = 1.0 + strength * np.sin(phase + offsets)
        weights = np.maximum(weights, 1e-3)
        return (weights / weights.sum()).astype(np.float32)

    @staticmethod
    def _circular_distance(a: np.ndarray | float, b: float, size: int) -> np.ndarray:
        raw = np.abs(np.asarray(a, dtype=np.float32) - float(b))
        return np.minimum(raw, float(size) - raw)

    def node_arrival_rates(self, num_nodes: int, slow_epoch: int | None = None) -> np.ndarray:
        req_cfg = self.cfg["requests"]
        base_lambda = float(req_cfg["poisson_lambda"])
        node_cfg = req_cfg.get("node_distribution", {"mode": "uniform"})
        mode = node_cfg.get("mode", "uniform")
        if mode == "uniform" or slow_epoch is None:
            return np.full(num_nodes, base_lambda, dtype=np.float32)
        if mode != "drifting_hotspots":
            raise ValueError(f"Unsupported node_distribution.mode={mode!r}")

        strength = float(node_cfg.get("hotspot_strength", 0.75))
        width = max(float(node_cfg.get("hotspot_width", 2.0)), 1e-3)
        period = max(float(node_cfg.get("hotspot_period", 10)), 1.0)
        center = (float(slow_epoch) / period * float(num_nodes)) % float(num_nodes)
        nodes = np.arange(num_nodes, dtype=np.float32)
        dist = self._circular_distance(nodes, center, num_nodes)
        hotspot = np.exp(-(dist**2) / (2.0 * width**2))
        hotspot = hotspot / max(float(hotspot.mean()), 1e-6)
        rates = base_lambda * (1.0 + strength * (hotspot - 1.0))
        return np.maximum(rates, 0.05 * base_lambda).astype(np.float32)

    def node_service_probabilities(self, num_nodes: int, slow_epoch: int | None = None) -> np.ndarray:
        global_probs = self.service_probabilities(slow_epoch)
        node_cfg = self.cfg["requests"].get("node_distribution", {"mode": "uniform"})
        mode = node_cfg.get("mode", "uniform")
        if mode == "uniform" or slow_epoch is None:
            return np.tile(global_probs[None, :], (num_nodes, 1)).astype(np.float32)
        if mode != "drifting_hotspots":
            raise ValueError(f"Unsupported node_distribution.mode={mode!r}")

        strength = float(node_cfg.get("service_locality_strength", 0.65))
        width = max(float(node_cfg.get("hotspot_width", 2.0)), 1e-3)
        period = max(float(node_cfg.get("hotspot_period", 10)), 1.0)
        nodes = np.arange(num_nodes, dtype=np.float32)
        probs = np.zeros((num_nodes, len(self.service_stages)), dtype=np.float32)
        for i in range(len(self.service_stages)):
            center = ((float(slow_epoch) / period * float(num_nodes)) + i * num_nodes / len(self.service_stages)) % float(num_nodes)
            dist = self._circular_distance(nodes, center, num_nodes)
            local = np.exp(-(dist**2) / (2.0 * width**2))
            local = local / max(float(local.mean()), 1e-6)
            probs[:, i] = global_probs[i] * (1.0 + strength * (local - 1.0))
        probs = np.maximum(probs, 1e-6)
        probs /= probs.sum(axis=1, keepdims=True)
        return probs.astype(np.float32)

    def source_service_demand(self, num_nodes: int, slow_epoch: int | None = None) -> np.ndarray:
        rates = self.node_arrival_rates(num_nodes, slow_epoch)
        probs = self.node_service_probabilities(num_nodes, slow_epoch)
        return (rates[:, None] * probs).astype(np.float32)

    def sample_slot(self, num_nodes: int, slow_epoch: int | None = None) -> list[Request]:
        req_cfg = self.cfg["requests"]
        low = float(req_cfg["perturb_low"])
        high = float(req_cfg["perturb_high"])
        arrival_rates = self.node_arrival_rates(num_nodes, slow_epoch)
        service_probs_by_node = self.node_service_probabilities(num_nodes, slow_epoch)
        requests: list[Request] = []

        for node in range(num_nodes):
            arrivals = int(self.rng.poisson(float(arrival_rates[node])))
            for _ in range(arrivals):
                service_id = int(self.rng.choice(len(self.service_stages), p=service_probs_by_node[node]))
                stages = self.service_stages[service_id]
                user_id = int(self.rng.integers(0, self.users_per_node))

                compute = self.compute_base[service_id, :stages].copy()
                compute *= self.rng.uniform(low, high, size=stages)

                input_data = float(self.input_data_base[service_id] * self.rng.uniform(low, high))
                if stages > 1:
                    stage_data = self.stage_data_base[service_id, : stages - 1].copy()
                    stage_data *= self.rng.uniform(low, high, size=stages - 1)
                else:
                    stage_data = np.zeros(0, dtype=np.float32)

                requests.append(
                    Request(
                        request_id=self.next_request_id,
                        source_node=node,
                        user_id=user_id,
                        service_id=service_id,
                        compute=compute.astype(np.float32),
                        input_data=input_data,
                        stage_data=stage_data.astype(np.float32),
                    )
                )
                self.next_request_id += 1

        self.rng.shuffle(requests)
        return requests
